# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-05 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=64)),
                ('imageTitle', models.CharField(max_length=64, null=True)),
                ('opusImage', models.ImageField(upload_to='./static/upload/')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=64)),
                ('studentName', models.CharField(max_length=64)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(null=True)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
