# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sxEdu', '0002_auto_20160805_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='opusImage',
            field=models.ImageField(upload_to='./upload/'),
        ),
    ]
