# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-06 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sxEdu', '0003_auto_20160805_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='opusImage',
            field=models.ImageField(upload_to='/static/upload'),
        ),
    ]
