# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-06 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sxEdu', '0005_auto_20160806_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='opusImage',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
